"""primera creacion

Revision ID: e93af6032a19
Revises: 
Create Date: 2025-03-01 20:46:40.180179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93af6032a19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perro',
    sa.Column('id_perro', sa.Integer(), nullable=False),
    sa.Column('name_perro', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_perro')
    )
    op.create_index(op.f('ix_perro_id_perro'), 'perro', ['id_perro'], unique=False)
    op.create_index(op.f('ix_perro_name_perro'), 'perro', ['name_perro'], unique=False)
    op.create_index(op.f('ix_perro_owner'), 'perro', ['owner'], unique=True)
    op.create_table('persona',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('name_persona', sa.String(), nullable=True),
    sa.Column('email_oficina', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_index(op.f('ix_persona_email_oficina'), 'persona', ['email_oficina'], unique=True)
    op.create_index(op.f('ix_persona_id_persona'), 'persona', ['id_persona'], unique=False)
    op.create_index(op.f('ix_persona_name_persona'), 'persona', ['name_persona'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.drop_table('Equipo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Equipo',
    sa.Column('id_Equipo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_Deporte', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_persona_name_persona'), table_name='persona')
    op.drop_index(op.f('ix_persona_id_persona'), table_name='persona')
    op.drop_index(op.f('ix_persona_email_oficina'), table_name='persona')
    op.drop_table('persona')
    op.drop_index(op.f('ix_perro_owner'), table_name='perro')
    op.drop_index(op.f('ix_perro_name_perro'), table_name='perro')
    op.drop_index(op.f('ix_perro_id_perro'), table_name='perro')
    op.drop_table('perro')
    # ### end Alembic commands ###
